name: compile_time_regexp.h tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        os: [macos-latest, ubuntu-latest]
        cpp_compiler: [g++-13, clang++]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: macos-latest
            cpp_compiler: g++-13
          - os: ubuntu-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      run: pip install conan

    - name: Configure Conan
      run: conan profile detect

    - name: Install Requirements
      run: >
        conan install .
        --output-folder=${{ runner.workspace }}/build
        --build=missing -s compiler.cppstd=20
        -s build_type=${{ matrix.build_type }}

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: >
        cmake -B . -S ${{ github.workspace }}
        -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_TESTS=1

    - name: Build Test
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{ matrix.build_type }} --target tests

    - name: Run Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --test-dir tests --config ${{ matrix.build_type }}
